<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="4" ignored="41" total="47" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-24T00:43:30 CDT" name="Suite" finished-at="2025-05-24T00:44:22 CDT" duration-ms="51889">
    <groups>
      <group name="Array">
        <method signature="ArrayPageTest.submitInvalidCodeSqrsOfSortedArrayQtn(java.lang.String,java.lang.String)[pri:26, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" name="submitInvalidCodeSqrsOfSortedArrayQtn" class="dsAlgoTests.ArrayPageTest"/>
      </group> <!-- Array -->
    </groups>
    <test started-at="2025-05-24T00:43:30 CDT" name="DSAlgoTest" finished-at="2025-05-24T00:44:22 CDT" duration-ms="51889">
      <class name="dsAlgoTests.ArrayPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:31 CDT" name="setup" finished-at="2025-05-24T00:43:35 CDT" duration-ms="3541" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="userInHomePage()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:35 CDT" name="userInHomePage" finished-at="2025-05-24T00:43:36 CDT" duration-ms="1062" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userInHomePage -->
        <test-method retried="true" signature="submitInvalidCodeSqrsOfSortedArrayQtn(java.lang.String,java.lang.String)[pri:26, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:36 CDT" name="submitInvalidCodeSqrsOfSortedArrayQtn" data-provider="CodeTryEditor" finished-at="2025-05-24T00:43:39 CDT" duration-ms="3045" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[print("Hello, World!"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Error occurred during submission]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Error occurred during submission] but found [ No tests were collected]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgoTests.ArrayPageTest.submitInvalidCodeSqrsOfSortedArrayQtn(ArrayPageTest.java:308)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:39 CDT" name="teardown" finished-at="2025-05-24T00:43:40 CDT" duration-ms="1393" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:40 CDT" name="setup" finished-at="2025-05-24T00:43:43 CDT" duration-ms="3130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="userInHomePage()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:43 CDT" name="userInHomePage" finished-at="2025-05-24T00:43:45 CDT" duration-ms="1478" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userInHomePage -->
        <test-method retried="true" signature="submitInvalidCodeSqrsOfSortedArrayQtn(java.lang.String,java.lang.String)[pri:26, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:45 CDT" name="submitInvalidCodeSqrsOfSortedArrayQtn" data-provider="CodeTryEditor" finished-at="2025-05-24T00:43:47 CDT" duration-ms="2298" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[print("Hello, World!"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Error occurred during submission]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Error occurred during submission] but found [ No tests were collected]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgoTests.ArrayPageTest.submitInvalidCodeSqrsOfSortedArrayQtn(ArrayPageTest.java:308)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:47 CDT" name="teardown" finished-at="2025-05-24T00:43:49 CDT" duration-ms="1368" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:49 CDT" name="setup" finished-at="2025-05-24T00:43:52 CDT" duration-ms="3009" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="userInHomePage()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:52 CDT" name="userInHomePage" finished-at="2025-05-24T00:43:53 CDT" duration-ms="1529" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userInHomePage -->
        <test-method signature="submitInvalidCodeSqrsOfSortedArrayQtn(java.lang.String,java.lang.String)[pri:26, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:53 CDT" name="submitInvalidCodeSqrsOfSortedArrayQtn" data-provider="CodeTryEditor" finished-at="2025-05-24T00:43:55 CDT" duration-ms="2081" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[print("Hello, World!"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Error occurred during submission]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Error occurred during submission] but found [ No tests were collected]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgoTests.ArrayPageTest.submitInvalidCodeSqrsOfSortedArrayQtn(ArrayPageTest.java:308)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:56 CDT" name="teardown" finished-at="2025-05-24T00:43:57 CDT" duration-ms="1398" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:43:57 CDT" name="setup" finished-at="2025-05-24T00:44:00 CDT" duration-ms="3133" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="userInHomePage()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:44:00 CDT" name="userInHomePage" finished-at="2025-05-24T00:44:02 CDT" duration-ms="1584" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userInHomePage -->
        <test-method retried="true" signature="submitInvalidCodeSqrsOfSortedArrayQtn(java.lang.String,java.lang.String)[pri:26, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:44:02 CDT" name="submitInvalidCodeSqrsOfSortedArrayQtn" data-provider="CodeTryEditor" finished-at="2025-05-24T00:44:04 CDT" duration-ms="2178" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[print("Hello, World!")]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Error occurred during submission]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Error occurred during submission] but found [ No tests were collected]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgoTests.ArrayPageTest.submitInvalidCodeSqrsOfSortedArrayQtn(ArrayPageTest.java:308)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:44:04 CDT" name="teardown" finished-at="2025-05-24T00:44:05 CDT" duration-ms="619" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:44:05 CDT" name="setup" finished-at="2025-05-24T00:44:08 CDT" duration-ms="2978" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="userInHomePage()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:44:08 CDT" name="userInHomePage" finished-at="2025-05-24T00:44:09 CDT" duration-ms="1454" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userInHomePage -->
        <test-method retried="true" signature="submitInvalidCodeSqrsOfSortedArrayQtn(java.lang.String,java.lang.String)[pri:26, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:44:09 CDT" name="submitInvalidCodeSqrsOfSortedArrayQtn" data-provider="CodeTryEditor" finished-at="2025-05-24T00:44:11 CDT" duration-ms="2198" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[print("Hello, World!")]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Error occurred during submission]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Error occurred during submission] but found [ No tests were collected]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgoTests.ArrayPageTest.submitInvalidCodeSqrsOfSortedArrayQtn(ArrayPageTest.java:308)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:44:11 CDT" name="teardown" finished-at="2025-05-24T00:44:13 CDT" duration-ms="1408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:44:13 CDT" name="setup" finished-at="2025-05-24T00:44:16 CDT" duration-ms="3029" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="userInHomePage()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:44:16 CDT" name="userInHomePage" finished-at="2025-05-24T00:44:17 CDT" duration-ms="1436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userInHomePage -->
        <test-method signature="submitInvalidCodeSqrsOfSortedArrayQtn(java.lang.String,java.lang.String)[pri:26, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:44:17 CDT" name="submitInvalidCodeSqrsOfSortedArrayQtn" data-provider="CodeTryEditor" finished-at="2025-05-24T00:44:20 CDT" duration-ms="2246" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[print("Hello, World!")]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Error occurred during submission]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Error occurred during submission] but found [ No tests were collected]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgoTests.ArrayPageTest.submitInvalidCodeSqrsOfSortedArrayQtn(ArrayPageTest.java:308)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:dsAlgoTests.ArrayPageTest@7fc44dec]" started-at="2025-05-24T00:44:20 CDT" name="teardown" finished-at="2025-05-24T00:44:22 CDT" duration-ms="1372" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- dsAlgoTests.ArrayPageTest -->
    </test> <!-- DSAlgoTest -->
  </suite> <!-- Suite -->
</testng-results>
