<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KAITLYN" failures="1" tests="7" name="dsAlgoTests.DataStructurePageTest" time="55.041" errors="0" timestamp="2025-05-27T01:08:24 CDT" skipped="0">
  <testcase classname="dsAlgoTests.DataStructurePageTest" name="userInGetStartedDataStructurePage" time="4.985"/>
  <testcase classname="dsAlgoTests.DataStructurePageTest" name="userInTimeComplexityPage" time="5.260"/>
  <testcase classname="dsAlgoTests.DataStructurePageTest" name="userInTryEditorArraysInPython" time="5.935"/>
  <testcase classname="dsAlgoTests.DataStructurePageTest" name="userInPracticeQuestionsPage" time="17.281">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at dsAlgoTests.DataStructurePageTest.userInPracticeQuestionsPage(DataStructurePageTest.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- userInPracticeQuestionsPage -->
  <testcase classname="dsAlgoTests.DataStructurePageTest" name="runInvalidCodeInPaython" time="7.367"/>
  <testcase classname="dsAlgoTests.DataStructurePageTest" name="runInvalidCodeInPaython" time="7.077"/>
  <testcase classname="dsAlgoTests.DataStructurePageTest" name="validCodeTryEditorDataStructureInPython" time="7.136"/>
</testsuite> <!-- dsAlgoTests.DataStructurePageTest -->
