<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KAITLYN" failures="9" tests="76" name="dsAlgoTests.ArrayPageTest" time="566.025" errors="0" timestamp="2025-05-27T01:08:24 CDT" skipped="18">
  <testcase classname="dsAlgoTests.ArrayPageTest" name="userInGetStartedArrayPage" time="4.900"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="userInDropDownArrayPage" time="5.177"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="userInArraysInPython" time="5.532"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="userInTryEditorArraysInPython" time="6.684"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorsInPython" time="6.535"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorsInPython" time="6.943"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorsInPython" time="6.473">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorsInPython -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorsInPython" time="6.807">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorsInPython -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorsInPython" time="7.287">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at dsAlgoTests.ArrayPageTest.inValidCodeTryEditorsInPython(ArrayPageTest.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- inValidCodeTryEditorsInPython -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="validCodeTryEditorsInPython" time="6.986"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="practiseQtnsArraysInPython" time="6.463"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="searchTheArrayQtn" time="7.732"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runInvalidCodeSearchTheArray" time="7.557"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runInvalidCodeSearchTheArray" time="8.116"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runValidCodeSearchTheArray" time="7.955"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeSearchTheArray" time="8.270"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeSearchTheArray" time="9.141"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitValidCodeSearchTheArray" time="8.548">
    <skipped/>
  </testcase> <!-- submitValidCodeSearchTheArray -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitValidCodeSearchTheArray" time="8.549">
    <failure message="expected [Submission Successful] but found [ Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission Successful] but found [ Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgoTests.ArrayPageTest.submitValidCodeSearchTheArray(ArrayPageTest.java:147)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- submitValidCodeSearchTheArray -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitValidCodeSearchTheArray" time="9.123">
    <skipped/>
  </testcase> <!-- submitValidCodeSearchTheArray -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="maxConOnesQtn" time="7.511"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runInvalidCodeMaxConOnes" time="8.328"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runInvalidCodeMaxConOnes" time="7.582"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runValidCodeMaxConOnes" time="8.480"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeMaxConOnes" time="9.044"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeMaxConOnes" time="8.197"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitValidCodeMaxConOnes" time="8.097">
    <failure message="expected [Submission Successful] but found [ Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission Successful] but found [ Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgoTests.ArrayPageTest.submitValidCodeMaxConOnes(ArrayPageTest.java:209)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- submitValidCodeMaxConOnes -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitValidCodeMaxConOnes" time="8.079">
    <skipped/>
  </testcase> <!-- submitValidCodeMaxConOnes -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitValidCodeMaxConOnes" time="8.112">
    <skipped/>
  </testcase> <!-- submitValidCodeMaxConOnes -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="findEvenNumberQtn" time="7.581"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runInvalidCodeFindEvenNumber" time="8.226"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runInvalidCodeFindEvenNumber" time="7.937"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runValidFindEvenNumber" time="7.621"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeFindEvenNumber" time="7.935"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeFindEvenNumber" time="8.426"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitValidCodeFindEvenNumber" time="8.483"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="sqrsOfSortedArrayQtn" time="7.312"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runInvalidCodeSqrsOfSortedArrayQtn" time="7.162"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runInvalidCodeSqrsOfSortedArrayQtn" time="7.226"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="runValidSqrsOfSortedArrayQtn" time="7.778"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeSqrsOfSortedArrayQtn" time="8.175">
    <skipped/>
  </testcase> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeSqrsOfSortedArrayQtn" time="8.623">
    <skipped/>
  </testcase> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeSqrsOfSortedArrayQtn" time="8.610">
    <failure message="expected [Error occurred during submission] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgoTests.ArrayPageTest.submitInvalidCodeSqrsOfSortedArrayQtn(ArrayPageTest.java:320)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeSqrsOfSortedArrayQtn" time="8.913">
    <skipped/>
  </testcase> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeSqrsOfSortedArrayQtn" time="7.919">
    <failure message="expected [Error occurred during submission] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgoTests.ArrayPageTest.submitInvalidCodeSqrsOfSortedArrayQtn(ArrayPageTest.java:320)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitInvalidCodeSqrsOfSortedArrayQtn" time="9.240">
    <skipped/>
  </testcase> <!-- submitInvalidCodeSqrsOfSortedArrayQtn -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitValidCodeSqrsOfSortedArrayQtn" time="8.951">
    <failure message="expected [Submission Successful] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission Successful] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at dsAlgoTests.ArrayPageTest.submitValidCodeSqrsOfSortedArrayQtn(ArrayPageTest.java:333)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- submitValidCodeSqrsOfSortedArrayQtn -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitValidCodeSqrsOfSortedArrayQtn" time="8.517">
    <skipped/>
  </testcase> <!-- submitValidCodeSqrsOfSortedArrayQtn -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="submitValidCodeSqrsOfSortedArrayQtn" time="8.125">
    <skipped/>
  </testcase> <!-- submitValidCodeSqrsOfSortedArrayQtn -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="userInArraysUsingList" time="5.794"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="userInTryEditorArraysUsingList" time="6.697"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorsUsingList" time="6.620"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorsUsingList" time="6.727"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorsUsingList" time="6.596">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at dsAlgoTests.ArrayPageTest.inValidCodeTryEditorsUsingList(ArrayPageTest.java:364)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- inValidCodeTryEditorsUsingList -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorsUsingList" time="7.706">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorsUsingList -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorsUsingList" time="7.092">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorsUsingList -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="validCodeTryEditorsUsingList" time="6.898"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="practiseQtnsArraysUsingList" time="5.937"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="userInBasicOprtnsInList" time="5.591"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="userInTryEditorBasicOprtnsInList" time="7.053"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorBasicOprtnsInList" time="7.477">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at dsAlgoTests.ArrayPageTest.inValidCodeTryEditorBasicOprtnsInList(ArrayPageTest.java:416)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- inValidCodeTryEditorBasicOprtnsInList -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorBasicOprtnsInList" time="7.844"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorBasicOprtnsInList" time="7.002">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorBasicOprtnsInList -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorBasicOprtnsInList" time="6.667"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorBasicOprtnsInList" time="7.227">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorBasicOprtnsInList -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="validCodeTryEditorBasicOprtnsInList" time="7.234"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="userInApplicationsOfArray" time="6.229"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="practiseQtnsBasicOprtnsInList" time="6.810"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="userInTryEditorApplicationsOfArray" time="6.378"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorApplicationsOfArray" time="7.327"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorApplicationsOfArray" time="6.953">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at dsAlgoTests.ArrayPageTest.inValidCodeTryEditorApplicationsOfArray(ArrayPageTest.java:468)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- inValidCodeTryEditorApplicationsOfArray -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorApplicationsOfArray" time="6.937">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorApplicationsOfArray -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorApplicationsOfArray" time="6.921"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="inValidCodeTryEditorApplicationsOfArray" time="7.321">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorApplicationsOfArray -->
  <testcase classname="dsAlgoTests.ArrayPageTest" name="validCodeTryEditorApplicationsOfArray" time="7.123"/>
  <testcase classname="dsAlgoTests.ArrayPageTest" name="practiseQtnsApplicationsOfArray" time="6.896"/>
</testsuite> <!-- dsAlgoTests.ArrayPageTest -->
