<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KAITLYN" failures="8" tests="38" name="dsAlgoTests.QueuePageTest" time="691.882" errors="0" timestamp="2025-05-23T20:27:45 CDT" skipped="8">
  <testcase classname="dsAlgoTests.QueuePageTest" name="userInGetStartedQueuePage" time="16.208"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="userInDropDownQueuePage" time="17.203"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="userInImplOfQueue" time="17.320"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="userInTryEditorImplOfQueue" time="15.197"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplOfQueue" time="15.359"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplOfQueue" time="19.173"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplOfQueue" time="15.413">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorImplOfQueue -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplOfQueue" time="12.314">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at dsAlgoTests.QueuePageTest.inValidCodeTryEditorImplOfQueue(QueuePageTest.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- inValidCodeTryEditorImplOfQueue -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplOfQueue" time="15.785">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorImplOfQueue -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="validCodeTryEditorImplOfQueue" time="20.043"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="practiseQtnsImplOfQueue" time="28.347">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at dsAlgoTests.QueuePageTest.practiseQtnsImplOfQueue(QueuePageTest.java:87)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- practiseQtnsImplOfQueue -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="userInImplUsingCollections" time="13.376"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="userInTryEditorImplUsingCollections" time="16.028"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplUsingCollections" time="13.773"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplUsingCollections" time="20.194">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorImplUsingCollections -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplUsingCollections" time="19.409"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplUsingCollections" time="11.912">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorImplUsingCollections -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplUsingCollections" time="15.171">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at dsAlgoTests.QueuePageTest.inValidCodeTryEditorImplUsingCollections(QueuePageTest.java:118)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- inValidCodeTryEditorImplUsingCollections -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="validCodeTryEditorImplUsingCollections" time="30.741"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="practiseQtnsImplUsingCollections" time="24.076">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at dsAlgoTests.QueuePageTest.practiseQtnsImplUsingCollections(QueuePageTest.java:138)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- practiseQtnsImplUsingCollections -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="userInImplUsingArray" time="16.282"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="userInTryEditorImplUsingArray" time="15.390"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplUsingArray" time="15.247"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplUsingArray" time="20.890">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at dsAlgoTests.QueuePageTest.inValidCodeTryEditorImplUsingArray(QueuePageTest.java:169)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- inValidCodeTryEditorImplUsingArray -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplUsingArray" time="16.761">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorImplUsingArray -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplUsingArray" time="17.431">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorImplUsingArray -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorImplUsingArray" time="19.083"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="validCodeTryEditorImplUsingArray" time="16.272"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="practiseQtnsImplUsingArray" time="23.028">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at dsAlgoTests.QueuePageTest.practiseQtnsImplUsingArray(QueuePageTest.java:189)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- practiseQtnsImplUsingArray -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="userInQueueOperation" time="15.447"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="userInTryEditorQueueOperation" time="19.018"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorQueueOperation" time="22.458">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at dsAlgoTests.QueuePageTest.inValidCodeTryEditorQueueOperation(QueuePageTest.java:220)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- inValidCodeTryEditorQueueOperation -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorQueueOperation" time="17.977">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorQueueOperation -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorQueueOperation" time="10.732">
    <skipped/>
  </testcase> <!-- inValidCodeTryEditorQueueOperation -->
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorQueueOperation" time="40.921"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="inValidCodeTryEditorQueueOperation" time="12.365"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="validCodeTryEditorQueueOperation" time="13.120"/>
  <testcase classname="dsAlgoTests.QueuePageTest" name="practiseQtnsQueueOperation" time="22.418">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at dsAlgoTests.QueuePageTest.practiseQtnsQueueOperation(QueuePageTest.java:240)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- practiseQtnsQueueOperation -->
</testsuite> <!-- dsAlgoTests.QueuePageTest -->
